import { AuthProvider } from "@/contexts/AuthContext";
import ApolloProvider from "@/providers/ApolloProvider";
import QueryProvider from "@/providers/QueryProvider";
import { Geist, Geist_Mono } from "next/font/google";

import Navbar from "@/components/navigation/Navbar";
import { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <QueryProvider>
            <ApolloProvider>
              <AuthProvider>
                <Navbar />
                <main>{children}</main>
              </AuthProvider>
            </ApolloProvider>
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
